### Tidy Tuesday Week 2

```{r packages} 
library('ggplot2')
library('dplyr')
```


```{r import_data}

freedom <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-02-22/freedom.csv')

skimr::skim(freedom)

freedom %>% dplyr::summarize(Min_PR = min(PR),
                             Max_PR = max(PR),
                             mean_PR = mean(PR))

americas_df <- freedom %>% dplyr::filter(Region_Name=='Americas')
americas_df %>% group_by(year, country) %>% count(country) %>% dplyr::filter(n>1)

plotly::ggplotly({americas_df %>% group_by(country) %>% dplyr::summarize(PR=mean(PR), CL = mean(CL)) %>%
  ggplot(aes(x=CL,y=PR, color=country)) + geom_point() + 
    theme(legend.position = 'none')})

avg_df <- freedom %>%
  group_by(year) %>%
  summarize(avg_CL = mean(CL),
            avg_PR = mean(PR))

usa_df <- freedom %>% dplyr::filter(country == 'United States of America') %>%
  dplyr::full_join(avg_df,by = c('year'='year')) %>%
  dplyr::group_by(year) %>%
  dplyr::mutate(rat_PR = PR/avg_PR,
                rat_CL = CL/avg_CL,
                rat_Index = 1-(PR + CL)/(avg_PR+avg_CL),
                sum_vars = CL + PR,
                freedom_score = 0.5*(100-(PR - 1)*100/6) + 0.5*(100-(CL - 1)*100/6))

usa_df %>% 
  dplyr::filter(year >= 2008, year <= 2017) %>% 
  dplyr::mutate(FreedomIndex = freedom_score) %>%
  ggplot(aes(x=year,y=FreedomIndex)) + geom_line()
                      

```